CREATE TABLE `artifact` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `status` bigint unsigned NOT NULL DEFAULT '1',
  `storage_place` bigint unsigned NOT NULL,
  `inventory` varchar(25) DEFAULT NULL,
  `conservation_state` bigint unsigned NOT NULL,
  `object_condition` bigint unsigned DEFAULT '1',
  `is_museum_copy` tinyint(1) DEFAULT '0',
  `category_class` bigint unsigned NOT NULL,
  `category_specs` bigint unsigned DEFAULT NULL,
  `type` text,
  `start` int DEFAULT NULL,
  `end` int DEFAULT NULL,
  `description` text,
  `notes` text,
  `author` int NOT NULL,
  `owner` bigint unsigned NOT NULL,
  `license` bigint unsigned NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `last_update` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `uuid` varchar(36) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `artifact_unique` (`name`),
  KEY `art_status_fk` (`status`),
  KEY `art_place_fk` (`storage_place`),
  KEY `art_conservation_state_fk` (`conservation_state`),
  KEY `art_obj_condition_fk` (`object_condition`),
  KEY `art_cat_class_fk` (`category_class`),
  KEY `art_cat_specs_fk` (`category_specs`),
  KEY `artifact_author_fki` (`author`),
  KEY `artifact_owner_fki` (`owner`),
  KEY `artifact_license_fki` (`license`),
  CONSTRAINT `art_cat_class_fk` FOREIGN KEY (`category_class`) REFERENCES `list_category_class` (`id`) ON DELETE CASCADE,
  CONSTRAINT `art_cat_specs_fk` FOREIGN KEY (`category_specs`) REFERENCES `list_category_specs` (`id`) ON DELETE CASCADE,
  CONSTRAINT `art_conservation_state_fk` FOREIGN KEY (`conservation_state`) REFERENCES `list_conservation_state` (`id`) ON DELETE CASCADE,
  CONSTRAINT `art_obj_condition_fk` FOREIGN KEY (`object_condition`) REFERENCES `list_object_condition` (`id`) ON DELETE CASCADE,
  CONSTRAINT `art_place_fk` FOREIGN KEY (`storage_place`) REFERENCES `institution` (`id`) ON DELETE CASCADE,
  CONSTRAINT `art_status_fk` FOREIGN KEY (`status`) REFERENCES `list_item_status` (`id`) ON DELETE CASCADE,
  CONSTRAINT `artifact_author_fki` FOREIGN KEY (`author`) REFERENCES `user` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `artifact_license_fki` FOREIGN KEY (`license`) REFERENCES `license` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `artifact_owner_fki` FOREIGN KEY (`owner`) REFERENCES `institution` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `check_artifact_chrono` CHECK ((`end` >= `start`))
) ENGINE=InnoDB AUTO_INCREMENT=427 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci